version: '3.0'
services:
  app:
    env_file:
      - .env
    depends_on:
      - cache
      - db
    build: .
    ports:
      - 8081:8080
  cache:
    image: redis:latest
  db:
    image: mongo:latest
